SELECT * FROM Gold_Fact_Sales S
--SELECT * FROM Gold_Dim_Products P
SELECT * FROM Gold_Dim_Customers C


---Find total customers by Countries??
SELECT 
Country,
COUNT(Customer_Key) AS Total_Customers
FROM Gold_Dim_Customers
GROUP BY country
ORDER BY Total_Customers DESC

---Find total customers by Gender??

SELECT 
Gender,
COUNT(Customer_Key) AS Total_Customers
FROM Gold_Dim_Customers
group by Gender
order by Total_Customers desc


---Find total Products by Category??

SELECT
Category,
COUNT(Product_key) AS Total_Products
FROM Gold_Dim_Products
GROUP BY Category
ORDER BY Total_Products DESC

---What is the average cost in each category??

SELECT 
Category,
AVG(Cost) AS Average_Cost
FROM Gold_Dim_Products
GROUP BY Category
ORDER BY Average_Cost DESC

---What is the total revenue generated for each category??
SELECT 
p.Category,
sum(sales_amount) as Total_Revenue
FROM Gold_Fact_Sales S
left join Gold_Dim_Products P
on s.Product_Key = p.Product_Key
GROUP BY p.Category
ORDER BY Total_Revenue DESC

---Find total revenue generated by each customer??

SELECT 
c.Customer_Key,
c.first_name,
c.Last_name,
SUM(s.Sales_Amount)as [Total Revenue]
from Gold_Fact_Sales S
left join Gold_Dim_Customers c
on s.Customer_Key= c.customer_key
group by c.Customer_Key,
		 c.first_name,
		 c.Last_name
order by [Total Revenue] desc


---what is the distribution of sold items across countries??

SELECT 
C.Country,
SUM(S.Quantity) AS Total_Quantity_Sold
FROM Gold_Fact_Sales S
LEFT JOIN Gold_Dim_Customers C
ON S.Customer_Key = C.Customer_Key
GROUP BY C.Country
ORDER BY Total_Quantity_Sold DESC
